# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
name: Web App Quality
on:
  pull_request:
  merge_group:

jobs:
  lint:
    name: ðŸ”¬ Web App Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Install All
        uses: ./.github/workflows/compose/install-all

      - name: ðŸ”¬ Quality
        working-directory: web-app
        run: npm run quality
