# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
name: Scraper Quality
on:
  pull_request:
  merge_group:

jobs:
  lint:
    name: ğŸ”¬ Scraper Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: Pre Run
        uses: ./.github/workflows/compose/pre-run

      - name: ğŸ”¬ Quality
        working-directory: ./
        run: cd scraper && npm run quality
