# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
name: Web App
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  # Auto deploy daily to get the latest legislation data
  schedule:
    - cron: "0 6 * * *" # Run daily at 6:00 UTC (1am Central)

jobs:
  lint:
    name: ğŸ”¬ Web App Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ NPM Install
        working-directory: web-app
        run: npm i

      - name: ğŸ”¬ Quality
        working-directory: web-app
        run: npm run quality

  build-web-app:
    # only deploy main branch on pushes
    # if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    name: ğŸ—ï¸ Build Web App & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ NPM Install
        env:
          # Required for .env creation
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        working-directory: web-app
        run: npm i

      - name: ğŸ—ï¸ Build
        working-directory: web-app
        run: npm run build

      # Publish built files to GitHub Pages repo
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          repository-name: windy-civi/windy-civi.github.io
          folder: web-app/dist # The folder the action should deploy.
